### ISSUE TITLE
Заменить у участников команды недействующие ссылки на страницы в соц. сетях

### ISSUE THREAD

**Issue by ghost** [svetit/doika-landing#19]
**Шаги для воспроизведения:**
1. открыть раздел "Команда проекта";
2. перейти по ссылкам участников.

**Фактический результат:** при нажатии на ссылку пользователь перенаправлен на несуществующую страницу в соц. сетях. 

**Ожидаемый результат:** обновить ссылки.
![2](https://user-images.githubusercontent.com/46268205/55001473-b5571900-4fe5-11e9-80bd-ab879e55c341.png)

**Comment by svetit** [comment]
Дадаць для усіх нашых рабят спасылкі на іх старонкі у вікі (замест тых, што зараз)
Тут шукаць https://wiki.falanster.info/wiki/Doika

**Comment by KahjuksEi** [comment]
done

**Comment by ghost** [comment]
@svetit ссылка на wiki должна быть у **каждого** участника?

**Comment by svetit** [comment]
@Olya147 Так, прапаную кожнага, у каго есць спасылкі. Здаецца, іх няма толькі у Светы Назаравай і Сёмкі пакуль што. Астатніх - замяніць.
Задачка працягваецца.

**Comment by ghost** [comment]
@KahjuksEi нужно поменять ссылки всем участникам.

**Comment by KahjuksEi** [comment]
done

**Comment by svetit** [comment]
@Olya147 правер, калі ласка зараз.
