### ISSUE TITLE
Исправить орфографические ошибки в бел. версии сайта

### ISSUE THREAD

**Issue by ghost** [svetit/doika-landing#20]
**Шаги для воспроизведения:**
1. Открыть белорусскую версию сайта

**Фактический результат:** страница содержит орфографические ошибки.

![3](https://user-images.githubusercontent.com/46268205/55025901-e437b400-5012-11e9-862e-53aba2c29545.png)
![4](https://user-images.githubusercontent.com/46268205/55025902-e437b400-5012-11e9-87c0-04af272bb171.png)
![5](https://user-images.githubusercontent.com/46268205/55025904-e437b400-5012-11e9-945d-3f1cd6ae8c5a.png)

**Comment by svetit** [comment]
Здаецца, што  форма "вашыя" таксама мае месца быць.
Але усе астатнія памылкі ватра выправіць!
Можна брацца за задачу.

**Comment by KahjuksEi** [comment]
done
