### ISSUE TITLE
Дополнить перевод русскоязычной версии сайта

### ISSUE THREAD

**Issue by ghost** [svetit/doika-landing#21]
**Шаги воспроизведения:**
1. Открыть русскую версию сайта

**Фактический результат:** текст в белорусской и русской версиях сайта не совпадает. 

![6](https://user-images.githubusercontent.com/46268205/55029061-34fedb00-501a-11e9-8909-c8320f3a3e2f.png)

**Comment by svetit** [comment]
Можна брацца за гэтую задачу!

**Comment by KahjuksEi** [comment]
done
