### ISSUE TITLE
Строка с названиями вкладок блокирует кнопку выхода из инструкции

### ISSUE THREAD

**Issue by ghost** [svetit/doika-landing#24]
**Шаги для воспроизведения:**
1. перейти в раздел "Поддержать"
2. нажать на "Аписанне спосабу аплаты".

**Фактический результат:**  строка вкладок перекрывает и блокирует кнопку "Х". Форма не реагирует на кнопку Esc.
Закрыть инструкцию можно лишь щёлкнув в область за её пределами. 

**Ожидаемый результат:** инструкция расположена ниже. После нажатия на "Х" форма закрывается.
![6](https://user-images.githubusercontent.com/46268205/55227201-e0c94600-5227-11e9-96e3-d41e36aff020.png)

**Comment by svetit** [comment]
З гэтай задачкай трэба разабрацца. Здаецца гэта верстка самога модуля, а не сайта.
@Olya147 
Пракаментуй тут, калі ласка, @fr0zen.

**Comment by fr0zen** [comment]
@svetit фіксануў

**Comment by ghost** [comment]
Исправлено.
