### ISSUE TITLE
Изменить ссылку для кнопки "Стань частью команды"

### ISSUE THREAD

**Issue by ghost** [svetit/doika-landing#26]
**Шаги воспроизведения:**
1. перейти в раздел "Команда";
2. нажать на кнопку "Стань частью команды"

**Фактический результат:** пользователь переходит в раздел "Контакт".

**Ожидаемый результат:** открывается анкета для стажёров/волонтёров (https://docs.google.com/forms/d/e/1FAIpQLSf78xrCLn3zsUaXmQGNrA58puu1Mk7AK4gIFyAwVXpNU1TyAw/viewform )

**Comment by svetit** [comment]
@Olya147 Пратэсціруй гэта, калі ласка.
@maxmatoha  пафіксіў.

**Comment by ghost** [comment]
Исправлено.
