### ISSUE TITLE
Ужать изображения в лэндинге

### ISSUE THREAD

**Issue by maxmatoha** [svetit/doika-landing#29]

**Comment by svetit** [comment]
@maxmatoha  Вітаю, змерджыла.
З кароўкай павінна быць выява у тэчцы img.
Перад табой яго спрабаваў зжаць @KahjuksEi 
(Не ведаю, як менавта).

И напишы, кали ласка, дзе и як ты сціскаў выявы, каб я магла гэта паўтарыць пры неабходнасці?

**Comment by maxmatoha** [comment]
https://tinypng.com -сжать .
А коровки в img нет.
В header.css   background-image: (такая ссылка)
url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACDQAAAKjCAMAAADfmT1OAAACr1BMVEUAAAAXGBcnLx8wMhpASSlLUiwbIRGYjlQfLB4oJiA1MSkfJg0oLA82OSEhKRcUHQ1bXjSmml9hZTk7QRtqbj2GfEMtOSgZJhg2QCVDQyEhIB+FjkuLhVCyomxANiEQEQ5VVDBze0YgHhl+dkaPlVoyPBhQWylzfT1PWTh9f0AbHQiOkE+hl1lHTDR+iUVxcEdAPSyPdkyqn2aAg03146tnbTJqeUCfj1V5fFFmYTCdk16BakWZllWkkl55YTmUfVNyWTcVFgSUiE+QiFiJcENlb0peYkR1hEhLQSpZXidMSiBJUD+DiFo0QDCPiEeIfUpweTQwKR1rUi5VYz1eZihSSTNvZzZmWDqGk1VRWUeAaDtrYkRdbTFGVCL26LN2cT1fbz4nIxNfViqchFd/dDqQmGicnl1TZC99jFA6MBpaVD1xbTmTf0eHhUBWTialqHBEQjZFShhQVR316MVfTDKxml/w3rt3ZETx26M8STZndjJZQSMoNRljaFVte1CGck49TBxZYk89OhL5883q1LGus3ubm3jgyat1emV3cFOfnGnVv6L48by7omVqcl2Fe1qNiWh+hW+TnltjSSbs1Jyai1+2r414hFuLknrJtZe0q2

**Comment by maxmatoha** [comment]
https://github.com/maxmatoha/bootstrap-doika-landing
мой вариант

**Comment by svetit** [comment]
@maxmatoha  Свой варыянт дадай у асобную ішшую.
І дадай лінк на сайт на гітхабе на прагляд, каб можна было яго праглядзець адразу.
І кідай у канад Дойкі на абмеркаванне.

п.с. тады кароўку паспрабую дадаць бліжэйшыям часам.
